sudo: true
language: java
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
  - sudo ant download-ivy -Dskip.download=false
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: ant test -Dskip.download=true
jdk:
  - oraclejdk8
 #- oraclejdk7 #  Jdk7 broken on container based trusty travis-ci#7019 
  - openjdk7

